server:
  port: 8080

spring:
  kafka:
    bootstrap-service: localhost:9092
  profiles:
    active: local
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_post_storage
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


